In [ ]:
# adding classic libraries...

In [16]:
import pandas as pd

In [17]:
import numpy as np

In [ ]:
# adding library that could help fetch kaggle dataset

In [5]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [22]:
file_path = kagglehub.dataset_download("lufasuch/wuthering-waves-characters")

In [ ]:
# trying to find where is the dataset stored

In [23]:
import os

In [24]:
os.listdir(file_path)

['wutheringwaves_character.csv']

In [27]:
print (file_path)

/home/codespace/.cache/kagglehub/datasets/lufasuch/wuthering-waves-characters/versions/1

In [28]:
file_path

'/home/codespace/.cache/kagglehub/datasets/lufasuch/wuthering-waves-characters/versions/1'

In [ ]:
# trying to show the data by using df

In [30]:
df = pd.read_csv(f"{file_path}/wutheringwaves_character.csv")

In [31]:
df.head()

,Character,Rarity,Weapon,Attribute,Role,Birthplace,Affiliation,HP,ATK,DEF
0,Rover - Spectro,5 Star,Sword,Spectro,Concerto Efficiency,Unknown,Unknown,912,30,112
1,Rover - Havoc,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,Unknown,866,33,103
2,Yangyang,4 Star,Sword,Aero,Concerto Efficiency,Huanglong,Jinzhou,816,20,90
3,Chixia,4 Star,Pistols,Fusion,Main Damage Dealer,Huanglong,Jinzhou,727,24,78
4,Baizhi,4 Star,Rectifier,Glacio,Support and Healer,Huanglong,Jinzhou,1025,17,82

In [33]:
df

,Character,Rarity,Weapon,Attribute,Role,Birthplace,Affiliation,HP,ATK,DEF
0,Rover - Spectro,5 Star,Sword,Spectro,Concerto Efficiency,Unknown,Unknown,912,30,112
1,Rover - Havoc,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,Unknown,866,33,103
2,Yangyang,4 Star,Sword,Aero,Concerto Efficiency,Huanglong,Jinzhou,816,20,90
3,Chixia,4 Star,Pistols,Fusion,Main Damage Dealer,Huanglong,Jinzhou,727,24,78
4,Baizhi,4 Star,Rectifier,Glacio,Support and Healer,Huanglong,Jinzhou,1025,17,82
5,Mortefi,4 Star,Pistols,Fusion,Concerto Efficiency,New Federation,Jinzhou,802,20,93
6,Danjin,4 Star,Sword,Havoc,Concerto Efficiency,Huanglong,Jinzhou,755,21,94
7,Aalto,4 Star,Pistols,Aero,Concerto Efficiency,New Federation,The Black Shores,788,21,88
8,Lingyang,4 Star,Gauntlets,Glacio,Main Damage Dealer,Huanglong,Jinzhou,831,35,99
9,Sanhua,4 Star,Sword,Glacio,Concerto Efficiency,Huanglong,Jinzhou,805,22,77
10,Jiyan,5 Star,Broadblade,Aero,Main Damage Dealer,Huanglong,Jinzhou,839,35,97
11,Yuanwu,4 Star,Gauntlets,Electro,Concerto Efficiency,Huanglong,Jinzhou,682,18,134
12,Verina,5 Star,Rectifier,Spectro,Support and Healer,New Federation,Jinzhou,1139,27,90
13,Calcharo,5 Star,Broadblade,Electro,Main Damage Dealer,New Federation,Ghost Hounds,840,35,97
14,Taoqi,4 Star,Broadblade,Havoc,Support and Healer,Huanglong,Jinzhou,716,18,128
15,Yinlin,5 Star,Rectifier,Electro,Concerto Efficiency,Huanglong,Jinzhou,880,32,105
16,Jinhsi,5 Star,Broadblade,Spectro,Main Damage Dealer,Huanglong,Jinzhou,866,33,103
17,Changli,5 Star,Sword,Fusion,Main Damage Dealer,Huanglong,Jinzhou,831,37,90
18,Zhezhi,5 Star,Rectifier,Glacio,Concerto Efficiency,Huanglong,Jinzhou,980,30,98
19,Xiangli Yao,5 Star,Gauntlets,Electro,Main Damage Dealer,Huanglong,Jinzhou,850,34,100
20,Shorekeeper,5 Star,Rectifier,Spectro,Support and Healer,The Black Shores,The Black Shores,1337,23,90
21,Youhu,4 Star,Gauntlets,Glacio,Support and Healer,Huanglong,Chongzou,798,21,86
22,Camellya,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,The Black Shores,826,36,95
23,Encore,5 Star,Rectifier,Fusion,Main Damage Dealer,New Federation,The Black Shores,841,34,102
24,Lumi,4 Star,Broadblade,Electro,Main Damage Dealer,Huanglong,Lollo Logistics,680,27,72
25,Carlotta,5 Star,Pistols,Glacio,Main Damage Dealer,Ragunna,The Montelli Family,996,37,98
26,Jianxin,5 Star,Gauntlets,Aero,Support and Healer,Huanglong,Jinzhou,1129,27,92
27,Roccia,5 Star,Gauntlets,Havoc,Concerto Efficiency,Rinascita,Troupe of Fools,980,30,98
28,Phoebe,5 Star,Rectifier,Spectro,Main Damage Dealer,Rinascita,Order of the Deep,866,33,103
29,Brant,5 Star,Sword,Fusion,Support and Healer,Rinascita,Troupe of Fools,934,30,107
30,Rover - Aero,5 Star,Sword,Aero,Support and Healer,Unknown,Unknown,862,35,93
31,Cantarella,5 Star,Rectifier,Havoc,Concerto Efficiency,Rinascita,The Fisalia Family,928,32,90

# Churn Prediction Project Nahhh Rarity Prediction Project

### notes for ML Zoomcamp 3.1 Youtube

In [ ]:
# customer churn -> using Binary Classification
# here we use wuwa dataset so "rarity" will be our y = g (x)
# likelihood of (churn?? no.) rarity hehehe

# the dataset comes from kaggle (youtube use telco churn, me use wuwa chara)

# what we gonna do, preparation, using scikit learn, and then eda, we gon categorical variable

# some logistic regression, versus it against linear regression

# point is talked about the big plan

In [39]:
# notes for ML Zoomcamp 3.2 Youtube 

#get the data, i already done, using kaggle method

In [48]:
df = pd.read_csv(f"{file_path}/wutheringwaves_character.csv")

In [50]:
df.head() #show 5 index

,Character,Rarity,Weapon,Attribute,Role,Birthplace,Affiliation,HP,ATK,DEF
0,Rover - Spectro,5 Star,Sword,Spectro,Concerto Efficiency,Unknown,Unknown,912,30,112
1,Rover - Havoc,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,Unknown,866,33,103
2,Yangyang,4 Star,Sword,Aero,Concerto Efficiency,Huanglong,Jinzhou,816,20,90
3,Chixia,4 Star,Pistols,Fusion,Main Damage Dealer,Huanglong,Jinzhou,727,24,78
4,Baizhi,4 Star,Rectifier,Glacio,Support and Healer,Huanglong,Jinzhou,1025,17,82

In [98]:
# youtube video does the data preparation (fixing the uppercase lowercase for the column)

df.columns = df.columns.str.lower().str.replace(' ','_') # the replace... its like replacing space with underscore

categorical_columns = list(df.dtypes[df.dtypes == 'string'].index) # act as a filter to grab the data names of all the collumns in your dataset that contain text! in this case string!

for c in categorical_columns: # this loop function would format all the data
    df[c]=df[c].str.lower().str.replace(' ','_') # this will like make the data uniform "all on lowercase, and underscore replace the space"

In [99]:
df.head()

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,rover_spectro,5_star,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
1,rover_havoc,5_star,sword,havoc,main_damage_dealer,unknown,unknown,866,33,103
2,yangyang,4_star,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
3,chixia,4_star,pistols,fusion,main_damage_dealer,huanglong,jinzhou,727,24,78
4,baizhi,4_star,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82

In [100]:
df['character'] = df['character'].str.replace('___','_') # format the character collumn data triple underscore to just one underscore
df.head()

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,rover_spectro,5_star,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
1,rover_havoc,5_star,sword,havoc,main_damage_dealer,unknown,unknown,866,33,103
2,yangyang,4_star,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
3,chixia,4_star,pistols,fusion,main_damage_dealer,huanglong,jinzhou,727,24,78
4,baizhi,4_star,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82

In [101]:
df.dtypes #checking the data types (he change the datatypes to numeric by pd.to_numeric(df."collumnname")
# mine is all good, so... turn to numeric like 

# tc = pd.to_numeric(df.totalcharges, errors='coerce)
# tc.isnull().sum() 'see how many missing
# df [tc.isnull().sum()] 'see the data
# df [tc.isnull().sum()]['customerid', 'totalcharges']] 'see morreee of the data

# and then he want to replace the totalcharges missingvalues to zero

# df.totalcharges = df.totalcharges.fillna(0)

character        str
rarity           str
weapon           str
attribute        str
role             str
birthplace       str
affiliation      str
hp             int64
atk            int64
def            int64
dtype: object

In [105]:
# look at the churn variable (no no), look at the rarity variable

df.rarity.head()

0    5_star
1    5_star
2    4_star
3    4_star
4    4_star
Name: rarity, dtype: str

In [102]:
# Turn the 5 4 star to true false

(df.rarity == '5_star').head()

0     True
1     True
2    False
3    False
4    False
Name: rarity, dtype: bool

In [106]:
# Turn the true false to 1 0

(df.rarity == '5_star').astype(int).head()

0    1
1    1
2    0
3    0
4    0
Name: rarity, dtype: int64

In [ ]:
# yea this just turn our rarity variable to a binary one

# 3,3 Setting up the Validation Framework 

### Notes for ML Zoomcamp Youtube Part 3