In [10]:
# adding classic libraries...

In [11]:
import pandas as pd

In [12]:
import numpy as np

In [13]:
# adding library that could help fetch kaggle dataset

In [14]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [15]:
file_path = kagglehub.dataset_download("lufasuch/wuthering-waves-characters")

In [16]:
# trying to find where is the dataset stored

In [17]:
import os

In [18]:
os.listdir(file_path)

['wutheringwaves_character.csv']

In [19]:
print (file_path)

/home/codespace/.cache/kagglehub/datasets/lufasuch/wuthering-waves-characters/versions/1

In [20]:
file_path

'/home/codespace/.cache/kagglehub/datasets/lufasuch/wuthering-waves-characters/versions/1'

In [21]:
# trying to show the data by using df

In [22]:
df = pd.read_csv(f"{file_path}/wutheringwaves_character.csv")

In [23]:
df.head()

,Character,Rarity,Weapon,Attribute,Role,Birthplace,Affiliation,HP,ATK,DEF
0,Rover - Spectro,5 Star,Sword,Spectro,Concerto Efficiency,Unknown,Unknown,912,30,112
1,Rover - Havoc,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,Unknown,866,33,103
2,Yangyang,4 Star,Sword,Aero,Concerto Efficiency,Huanglong,Jinzhou,816,20,90
3,Chixia,4 Star,Pistols,Fusion,Main Damage Dealer,Huanglong,Jinzhou,727,24,78
4,Baizhi,4 Star,Rectifier,Glacio,Support and Healer,Huanglong,Jinzhou,1025,17,82

In [24]:
df

,Character,Rarity,Weapon,Attribute,Role,Birthplace,Affiliation,HP,ATK,DEF
0,Rover - Spectro,5 Star,Sword,Spectro,Concerto Efficiency,Unknown,Unknown,912,30,112
1,Rover - Havoc,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,Unknown,866,33,103
2,Yangyang,4 Star,Sword,Aero,Concerto Efficiency,Huanglong,Jinzhou,816,20,90
3,Chixia,4 Star,Pistols,Fusion,Main Damage Dealer,Huanglong,Jinzhou,727,24,78
4,Baizhi,4 Star,Rectifier,Glacio,Support and Healer,Huanglong,Jinzhou,1025,17,82
5,Mortefi,4 Star,Pistols,Fusion,Concerto Efficiency,New Federation,Jinzhou,802,20,93
6,Danjin,4 Star,Sword,Havoc,Concerto Efficiency,Huanglong,Jinzhou,755,21,94
7,Aalto,4 Star,Pistols,Aero,Concerto Efficiency,New Federation,The Black Shores,788,21,88
8,Lingyang,4 Star,Gauntlets,Glacio,Main Damage Dealer,Huanglong,Jinzhou,831,35,99
9,Sanhua,4 Star,Sword,Glacio,Concerto Efficiency,Huanglong,Jinzhou,805,22,77
10,Jiyan,5 Star,Broadblade,Aero,Main Damage Dealer,Huanglong,Jinzhou,839,35,97
11,Yuanwu,4 Star,Gauntlets,Electro,Concerto Efficiency,Huanglong,Jinzhou,682,18,134
12,Verina,5 Star,Rectifier,Spectro,Support and Healer,New Federation,Jinzhou,1139,27,90
13,Calcharo,5 Star,Broadblade,Electro,Main Damage Dealer,New Federation,Ghost Hounds,840,35,97
14,Taoqi,4 Star,Broadblade,Havoc,Support and Healer,Huanglong,Jinzhou,716,18,128
15,Yinlin,5 Star,Rectifier,Electro,Concerto Efficiency,Huanglong,Jinzhou,880,32,105
16,Jinhsi,5 Star,Broadblade,Spectro,Main Damage Dealer,Huanglong,Jinzhou,866,33,103
17,Changli,5 Star,Sword,Fusion,Main Damage Dealer,Huanglong,Jinzhou,831,37,90
18,Zhezhi,5 Star,Rectifier,Glacio,Concerto Efficiency,Huanglong,Jinzhou,980,30,98
19,Xiangli Yao,5 Star,Gauntlets,Electro,Main Damage Dealer,Huanglong,Jinzhou,850,34,100
20,Shorekeeper,5 Star,Rectifier,Spectro,Support and Healer,The Black Shores,The Black Shores,1337,23,90
21,Youhu,4 Star,Gauntlets,Glacio,Support and Healer,Huanglong,Chongzou,798,21,86
22,Camellya,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,The Black Shores,826,36,95
23,Encore,5 Star,Rectifier,Fusion,Main Damage Dealer,New Federation,The Black Shores,841,34,102
24,Lumi,4 Star,Broadblade,Electro,Main Damage Dealer,Huanglong,Lollo Logistics,680,27,72
25,Carlotta,5 Star,Pistols,Glacio,Main Damage Dealer,Ragunna,The Montelli Family,996,37,98
26,Jianxin,5 Star,Gauntlets,Aero,Support and Healer,Huanglong,Jinzhou,1129,27,92
27,Roccia,5 Star,Gauntlets,Havoc,Concerto Efficiency,Rinascita,Troupe of Fools,980,30,98
28,Phoebe,5 Star,Rectifier,Spectro,Main Damage Dealer,Rinascita,Order of the Deep,866,33,103
29,Brant,5 Star,Sword,Fusion,Support and Healer,Rinascita,Troupe of Fools,934,30,107
30,Rover - Aero,5 Star,Sword,Aero,Support and Healer,Unknown,Unknown,862,35,93
31,Cantarella,5 Star,Rectifier,Havoc,Concerto Efficiency,Rinascita,The Fisalia Family,928,32,90

# 3.1 Churn Prediction Project??? Nahhh Rarity Prediction Project

### notes for ML Zoomcamp 3.1 Youtube

In [25]:
# customer churn -> using Binary Classification
# here we use wuwa dataset so "rarity" will be our y = g (x)
# likelihood of (churn?? no.) rarity hehehe

# the dataset comes from kaggle (youtube use telco churn, me use wuwa chara)

# what we gonna do, preparation, using scikit learn, and then eda, we gon categorical variable

# some logistic regression, versus it against linear regression

# point is talked about the big plan

# 3.2 Data Preparation

### notes for ML Zoomcamp 3.2 Youtube

In [26]:
# notes for ML Zoomcamp 3.2 Youtube 

#get the data, i already done, using kaggle method

In [27]:
df = pd.read_csv(f"{file_path}/wutheringwaves_character.csv")

In [28]:
df.head() #show 5 index

,Character,Rarity,Weapon,Attribute,Role,Birthplace,Affiliation,HP,ATK,DEF
0,Rover - Spectro,5 Star,Sword,Spectro,Concerto Efficiency,Unknown,Unknown,912,30,112
1,Rover - Havoc,5 Star,Sword,Havoc,Main Damage Dealer,Unknown,Unknown,866,33,103
2,Yangyang,4 Star,Sword,Aero,Concerto Efficiency,Huanglong,Jinzhou,816,20,90
3,Chixia,4 Star,Pistols,Fusion,Main Damage Dealer,Huanglong,Jinzhou,727,24,78
4,Baizhi,4 Star,Rectifier,Glacio,Support and Healer,Huanglong,Jinzhou,1025,17,82

In [29]:
# youtube video does the data preparation (fixing the uppercase lowercase for the column)

df.columns = df.columns.str.lower().str.replace(' ','_') # the replace... its like replacing space with underscore

categorical_columns = list(df.dtypes[df.dtypes == 'string'].index) # act as a filter to grab the data names of all the collumns in your dataset that contain text! in this case string!

for c in categorical_columns: # this loop function would format all the data
    df[c]=df[c].str.lower().str.replace(' ','_') # this will like make the data uniform "all on lowercase, and underscore replace the space"

In [30]:
df.head()

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,rover_-_spectro,5_star,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
1,rover_-_havoc,5_star,sword,havoc,main_damage_dealer,unknown,unknown,866,33,103
2,yangyang,4_star,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
3,chixia,4_star,pistols,fusion,main_damage_dealer,huanglong,jinzhou,727,24,78
4,baizhi,4_star,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82

In [47]:
df['character'] = df['character'].str.replace('_-_','_') # format the character collumn data triple underscore to just one underscore
df.head()

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,rover_spectro,5_star,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
1,rover_havoc,5_star,sword,havoc,main_damage_dealer,unknown,unknown,866,33,103
2,yangyang,4_star,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
3,chixia,4_star,pistols,fusion,main_damage_dealer,huanglong,jinzhou,727,24,78
4,baizhi,4_star,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82

In [48]:
df.dtypes #checking the data types (he change the datatypes to numeric by pd.to_numeric(df."collumnname")
# mine is all good, so... turn to numeric like 

# tc = pd.to_numeric(df.totalcharges, errors='coerce)
# tc.isnull().sum() 'see how many missing
# df [tc.isnull().sum()] 'see the data
# df [tc.isnull().sum()]['customerid', 'totalcharges']] 'see morreee of the data

# and then he want to replace the totalcharges missingvalues to zero

# df.totalcharges = df.totalcharges.fillna(0)

character        str
rarity           str
weapon           str
attribute        str
role             str
birthplace       str
affiliation      str
hp             int64
atk            int64
def            int64
dtype: object

In [49]:
# look at the churn variable (no no), look at the rarity variable

df.rarity.head()

0    5_star
1    5_star
2    4_star
3    4_star
4    4_star
Name: rarity, dtype: str

In [50]:
# Turn the 5 4 star to true false

(df.rarity == '5_star').head()

0     True
1     True
2    False
3    False
4    False
Name: rarity, dtype: bool

In [90]:
# Turn the true false to 1 0

(df.rarity == '5_star').astype(int).head()

0    1
1    1
2    0
3    0
4    0
Name: rarity, dtype: int64

In [52]:
# yea this just turn our rarity variable to a binary one

# 3.3 Setting up the Validation Framework 

### Notes for ML Zoomcamp Youtube Part 3

In [53]:
from sklearn.model_selection import train_test_split

In [56]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [57]:
len(df_full_train), len(df_test)

(25, 7)

In [55]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [58]:
len(df_train), len(df_val), len(df_test)

(18, 7, 7)

In [77]:
df_train = df_train.reset_index(drop=True) # tryna sort it  
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_ful_train = df_full_train.reset_index(drop=True)

In [78]:
df_val

,character,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,rover_havoc,sword,havoc,main_damage_dealer,unknown,unknown,866,33,103
1,brant,sword,fusion,support_and_healer,rinascita,troupe_of_fools,934,30,107
2,yinlin,rectifier,electro,concerto_efficiency,huanglong,jinzhou,880,32,105
3,lumi,broadblade,electro,main_damage_dealer,huanglong,lollo_logistics,680,27,72
4,lingyang,gauntlets,glacio,main_damage_dealer,huanglong,jinzhou,831,35,99
5,danjin,sword,havoc,concerto_efficiency,huanglong,jinzhou,755,21,94
6,cantarella,rectifier,havoc,concerto_efficiency,rinascita,the_fisalia_family,928,32,90

In [79]:
y_train = df_train.rarity.values
y_val = df_val.rarity.values
y_test = df_test.rarity.values

AttributeError: 'DataFrame' object has no attribute 'rarity'

In [81]:
# remove rarity dataframe from the table, bout to start training model!

del df_train['rarity']
del df_val['rarity']
del df_test['rarity']

KeyError: 'rarity'

In [82]:
df_train

,character,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,rover_aero,sword,aero,support_and_healer,unknown,unknown,862,35,93
1,jiyan,broadblade,aero,main_damage_dealer,huanglong,jinzhou,839,35,97
2,taoqi,broadblade,havoc,support_and_healer,huanglong,jinzhou,716,18,128
3,sanhua,sword,glacio,concerto_efficiency,huanglong,jinzhou,805,22,77
4,jianxin,gauntlets,aero,support_and_healer,huanglong,jinzhou,1129,27,92
5,baizhi,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82
6,verina,rectifier,spectro,support_and_healer,new_federation,jinzhou,1139,27,90
7,xiangli_yao,gauntlets,electro,main_damage_dealer,huanglong,jinzhou,850,34,100
8,rover_spectro,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
9,phoebe,rectifier,spectro,main_damage_dealer,rinascita,order_of_the_deep,866,33,103
10,jinhsi,broadblade,spectro,main_damage_dealer,huanglong,jinzhou,866,33,103
11,mortefi,pistols,fusion,concerto_efficiency,new_federation,jinzhou,802,20,93
12,yuanwu,gauntlets,electro,concerto_efficiency,huanglong,jinzhou,682,18,134
13,carlotta,pistols,glacio,main_damage_dealer,ragunna,the_montelli_family,996,37,98
14,yangyang,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
15,aalto,pistols,aero,concerto_efficiency,new_federation,the_black_shores,788,21,88
16,calcharo,broadblade,electro,main_damage_dealer,new_federation,ghost_hounds,840,35,97
17,shorekeeper,rectifier,spectro,support_and_healer,the_black_shores,the_black_shores,1337,23,90

In [74]:
# data_full_train is not delelting rarity because we need it for the "future look at the target variable"

# EDA

### notes

In [75]:
#check missing values
#look at the target variable (rarity)
#look at numerical and categorical variables

In [83]:
df_full_train.isnull().sum()

character      0
rarity         0
weapon         0
attribute      0
role           0
birthplace     0
affiliation    0
hp             0
atk            0
def            0
dtype: int64

In [84]:
#alr no missing value, all cool

In [85]:
df_full_train.rarity.value_counts()

rarity
5_star    15
4_star    10
Name: count, dtype: int64

In [86]:
df_full_train.rarity.value_counts(normalize=True)

rarity
5_star    0.6
4_star    0.4
Name: proportion, dtype: float64

In [87]:
# 0,6 is 5-star rarity rate

In [91]:
df_full_train.rarity.mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [92]:
df_full_train['rarity'] = (df_full_train['rarity'] == '5_star').astype(int)

In [93]:
df_full_train.rarity.mean()

np.float64(0.6)

In [124]:
global_rarity_rate = df_full_train.rarity.mean()
round(global_rarity_rate, 2)

np.float64(0.6)

In [97]:
df_full_train.dtypes

character        str
rarity         int64
weapon           str
attribute        str
role             str
birthplace       str
affiliation      str
hp             int64
atk            int64
def            int64
dtype: object

In [98]:
df_full_train.columns

Index(['character', 'rarity', 'weapon', 'attribute', 'role', 'birthplace',
       'affiliation', 'hp', 'atk', 'def'],
      dtype='str')

In [99]:
numerical = ['hp', 'atk','def']

In [100]:
categorical = ['character', 'rarity', 'weapon', 'attribute', 'role', 'birthplace',
       'affiliation']

In [102]:
df_full_train[categorical].nunique()

character      25
rarity          2
weapon          5
attribute       6
role            3
birthplace      6
affiliation     9
dtype: int64

# Feature Importance : 5 Star Rarity Rate and Risk Ratio

In [103]:
# Rarity Rate = 5 Star Rarity Rate

In [105]:
df_full_train.head()

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
28,phoebe,1,rectifier,spectro,main_damage_dealer,rinascita,order_of_the_deep,866,33,103
19,xiangli_yao,1,gauntlets,electro,main_damage_dealer,huanglong,jinzhou,850,34,100
14,taoqi,0,broadblade,havoc,support_and_healer,huanglong,jinzhou,716,18,128
24,lumi,0,broadblade,electro,main_damage_dealer,huanglong,lollo_logistics,680,27,72
10,jiyan,1,broadblade,aero,main_damage_dealer,huanglong,jinzhou,839,35,97

In [107]:
df_full_train = df_full_train.reset_index(drop=True)

In [116]:
df_full_train

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
0,phoebe,1,rectifier,spectro,main_damage_dealer,rinascita,order_of_the_deep,866,33,103
1,xiangli_yao,1,gauntlets,electro,main_damage_dealer,huanglong,jinzhou,850,34,100
2,taoqi,0,broadblade,havoc,support_and_healer,huanglong,jinzhou,716,18,128
3,lumi,0,broadblade,electro,main_damage_dealer,huanglong,lollo_logistics,680,27,72
4,jiyan,1,broadblade,aero,main_damage_dealer,huanglong,jinzhou,839,35,97
5,shorekeeper,1,rectifier,spectro,support_and_healer,the_black_shores,the_black_shores,1337,23,90
6,jianxin,1,gauntlets,aero,support_and_healer,huanglong,jinzhou,1129,27,92
7,baizhi,0,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82
8,yangyang,0,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
9,carlotta,1,pistols,glacio,main_damage_dealer,ragunna,the_montelli_family,996,37,98
10,danjin,0,sword,havoc,concerto_efficiency,huanglong,jinzhou,755,21,94
11,calcharo,1,broadblade,electro,main_damage_dealer,new_federation,ghost_hounds,840,35,97
12,aalto,0,pistols,aero,concerto_efficiency,new_federation,the_black_shores,788,21,88
13,brant,1,sword,fusion,support_and_healer,rinascita,troupe_of_fools,934,30,107
14,rover_havoc,1,sword,havoc,main_damage_dealer,unknown,unknown,866,33,103
15,jinhsi,1,broadblade,spectro,main_damage_dealer,huanglong,jinzhou,866,33,103
16,rover_spectro,1,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
17,yinlin,1,rectifier,electro,concerto_efficiency,huanglong,jinzhou,880,32,105
18,cantarella,1,rectifier,havoc,concerto_efficiency,rinascita,the_fisalia_family,928,32,90
19,rover_aero,1,sword,aero,support_and_healer,unknown,unknown,862,35,93
20,sanhua,0,sword,glacio,concerto_efficiency,huanglong,jinzhou,805,22,77
21,lingyang,0,gauntlets,glacio,main_damage_dealer,huanglong,jinzhou,831,35,99
22,verina,1,rectifier,spectro,support_and_healer,new_federation,jinzhou,1139,27,90
23,yuanwu,0,gauntlets,electro,concerto_efficiency,huanglong,jinzhou,682,18,134
24,mortefi,0,pistols,fusion,concerto_efficiency,new_federation,jinzhou,802,20,93

In [110]:
# now from here we tryna find out which variable could predict rarity the most

df_full_train[df_full_train.role == 'support_and_healer']

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
2,taoqi,0,broadblade,havoc,support_and_healer,huanglong,jinzhou,716,18,128
5,shorekeeper,1,rectifier,spectro,support_and_healer,the_black_shores,the_black_shores,1337,23,90
6,jianxin,1,gauntlets,aero,support_and_healer,huanglong,jinzhou,1129,27,92
7,baizhi,0,rectifier,glacio,support_and_healer,huanglong,jinzhou,1025,17,82
13,brant,1,sword,fusion,support_and_healer,rinascita,troupe_of_fools,934,30,107
19,rover_aero,1,sword,aero,support_and_healer,unknown,unknown,862,35,93
22,verina,1,rectifier,spectro,support_and_healer,new_federation,jinzhou,1139,27,90

In [114]:
rarity_support_and_healer = df_full_train[df_full_train.role == 'support_and_healer'].rarity.mean()

In [115]:
rarity_main_damage_dealer = df_full_train[df_full_train.role == 'main_damage_dealer'].rarity.mean()

In [118]:
df_full_train[df_full_train.role == 'concerto_efficiency']

,character,rarity,weapon,attribute,role,birthplace,affiliation,hp,atk,def
8,yangyang,0,sword,aero,concerto_efficiency,huanglong,jinzhou,816,20,90
10,danjin,0,sword,havoc,concerto_efficiency,huanglong,jinzhou,755,21,94
12,aalto,0,pistols,aero,concerto_efficiency,new_federation,the_black_shores,788,21,88
16,rover_spectro,1,sword,spectro,concerto_efficiency,unknown,unknown,912,30,112
17,yinlin,1,rectifier,electro,concerto_efficiency,huanglong,jinzhou,880,32,105
18,cantarella,1,rectifier,havoc,concerto_efficiency,rinascita,the_fisalia_family,928,32,90
20,sanhua,0,sword,glacio,concerto_efficiency,huanglong,jinzhou,805,22,77
23,yuanwu,0,gauntlets,electro,concerto_efficiency,huanglong,jinzhou,682,18,134
24,mortefi,0,pistols,fusion,concerto_efficiency,new_federation,jinzhou,802,20,93

In [121]:
rarity_concerto_efficiency = df_full_train[df_full_train.role == 'concerto_efficiency'].rarity.mean()

In [122]:
global_rarity = df_full_train.rarity.mean()

In [123]:
global_rarity

np.float64(0.6)

In [135]:
df_full_train.atk.value_counts()

atk
35    4
33    3
27    3
18    2
20    2
21    2
30    2
32    2
34    1
23    1
17    1
37    1
22    1
Name: count, dtype: int64

In [196]:
df_full_train['def'].value_counts()

def
90     4
103    3
97     2
93     2
100    1
128    1
72     1
92     1
82     1
98     1
94     1
88     1
107    1
112    1
105    1
77     1
99     1
134    1
Name: count, dtype: int64

In [204]:
rarity_high_hp = df_full_train[df_full_train.hp >= 835].rarity.mean()
rarity_high_hp

np.float64(0.9375)

In [209]:
rarity_low_hp = df_full_train[df_full_train.hp < 835].rarity.mean()
rarity_low_hp #means in this data_full_train no one is <835

np.float64(0.0)

In [212]:
rarity_low_def = df_full_train[df_full_train['def'] < 90].rarity.mean()
rarity_low_def

np.float64(0.0)

In [213]:
rarity_high_def = df_full_train[df_full_train['def'] >= 90].rarity.mean()
rarity_high_def

np.float64(0.7142857142857143)

In [136]:
rarity_high_atk = df_full_train[df_full_train.atk >= 30].rarity.mean()

In [137]:
rarity_high_atk

np.float64(0.9230769230769231)

In [138]:
rarity_low_atk = df_full_train[df_full_train.atk < 30].rarity.mean()

In [139]:
rarity_low_atk

np.float64(0.25)

In [140]:
global_rarity - rarity_high_atk

np.float64(-0.32307692307692315)

In [141]:
global_rarity - rarity_low_atk

np.float64(0.35)

In [142]:
global_rarity - rarity_main_damage_dealer

np.float64(-0.1777777777777778)

In [143]:
global_rarity - rarity_support_and_healer

np.float64(-0.11428571428571432)

In [145]:
global_rarity - rarity_concerto_efficiency

np.float64(0.26666666666666666)

In [162]:
# the difference from atk is so much bigger, means is more influenceal to rarity

# global - group -> if its > 0 less likely to rare, if its < 0 more likely to rare

In [ ]:
# risk ratio

In [147]:
rarity_high_atk/global_rarity

np.float64(1.5384615384615385)

In [148]:
rarity_low_atk/global_rarity

np.float64(0.4166666666666667)

In [149]:
# risk ratio if >1 then more likely is rare, if < 1 no likely rare

In [172]:
#calculating rarity by atk

high_atk = np.where(df_full_train['atk'] >= 30, '>=30', '<30')

df_group = df_full_train.groupby(high_atk).rarity.agg(['mean','count'])

df_group

          mean  count
<30   0.250000     12
>=30  0.923077     13

In [161]:
df_group['diff'] = df_group['mean']- global_rarity
df_group['risk'] = df_group['mean']/global_rarity
df_group

          mean  count      diff      risk
<30   0.250000     12 -0.350000  0.416667
>=30  0.923077     13  0.323077  1.538462

In [164]:
for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).rarity.agg(['mean','count'])
    df_group['diff'] = df_group['mean']- global_rarity
    df_group['risk'] = df_group['mean']/global_rarity
    display(df_group)

character

               mean  count  diff      risk
character
aalto           0.0      1  -0.6  0.000000
baizhi          0.0      1  -0.6  0.000000
brant           1.0      1   0.4  1.666667
calcharo        1.0      1   0.4  1.666667
cantarella      1.0      1   0.4  1.666667
carlotta        1.0      1   0.4  1.666667
danjin          0.0      1  -0.6  0.000000
jianxin         1.0      1   0.4  1.666667
jinhsi          1.0      1   0.4  1.666667
jiyan           1.0      1   0.4  1.666667
lingyang        0.0      1  -0.6  0.000000
lumi            0.0      1  -0.6  0.000000
mortefi         0.0      1  -0.6  0.000000
phoebe          1.0      1   0.4  1.666667
rover_aero      1.0      1   0.4  1.666667
rover_havoc     1.0      1   0.4  1.666667
rover_spectro   1.0      1   0.4  1.666667
sanhua          0.0      1  -0.6  0.000000
shorekeeper     1.0      1   0.4  1.666667
taoqi           0.0      1  -0.6  0.000000
verina          1.0      1   0.4  1.666667
xiangli_yao     1.0      1   0.4  1.666667
yangyang        0.0      1  -0.6  0.000000
yinlin          1.0      1   0.4  1.666667
yuanwu          0.0      1  -0.6  0.000000

rarity

        mean  count  diff      risk
rarity
0        0.0     10  -0.6  0.000000
1        1.0     15   0.4  1.666667

weapon

                mean  count      diff      risk
weapon
broadblade  0.600000      5  0.000000  1.000000
gauntlets   0.500000      4 -0.100000  0.833333
pistols     0.333333      3 -0.266667  0.555556
rectifier   0.833333      6  0.233333  1.388889
sword       0.571429      7 -0.028571  0.952381

attribute

           mean  count  diff      risk
attribute
aero       0.60      5  0.00  1.000000
electro    0.60      5  0.00  1.000000
fusion     0.50      2 -0.10  0.833333
glacio     0.25      4 -0.35  0.416667
havoc      0.50      4 -0.10  0.833333
spectro    1.00      5  0.40  1.666667

role

                         mean  count      diff      risk
role
concerto_efficiency  0.333333      9 -0.266667  0.555556
main_damage_dealer   0.777778      9  0.177778  1.296296
support_and_healer   0.714286      7  0.114286  1.190476

birthplace

                      mean  count      diff      risk
birthplace
huanglong         0.384615     13 -0.215385  0.641026
new_federation    0.500000      4 -0.100000  0.833333
ragunna           1.000000      1  0.400000  1.666667
rinascita         1.000000      3  0.400000  1.666667
the_black_shores  1.000000      1  0.400000  1.666667
unknown           1.000000      3  0.400000  1.666667

affiliation

                         mean  count      diff      risk
affiliation
ghost_hounds         1.000000      1  0.400000  1.666667
jinzhou              0.428571     14 -0.171429  0.714286
lollo_logistics      0.000000      1 -0.600000  0.000000
order_of_the_deep    1.000000      1  0.400000  1.666667
the_black_shores     0.500000      2 -0.100000  0.833333
the_fisalia_family   1.000000      1  0.400000  1.666667
the_montelli_family  1.000000      1  0.400000  1.666667
troupe_of_fools      1.000000      1  0.400000  1.666667
unknown              1.000000      3  0.400000  1.666667

In [165]:
# in youtube the categorical is likemost of it 2 rows

In [166]:
# aight caught up to 3.6

In [ ]:
# we cant sat atk information is more important than other and other is less important

# Feature Importance: Mutual Information

In [167]:
# is like if we got this atk data, how rare it is, or other variabls other than attack treat the same

In [168]:
# we use scikit learn

In [169]:
from sklearn.metrics import mutual_info_score

In [197]:
mutual_info_score(df_full_train['def'], df_full_train.rarity)

0.5275862694254516

In [187]:
mutual_info_score(df_full_train.hp, df_full_train.rarity)

0.673011667009257

In [174]:
mutual_info_score(df_full_train.atk, df_full_train.rarity)

0.5066563436748696

In [175]:
mutual_info_score(df_full_train.role, df_full_train.rarity)

0.08565684995849585

In [177]:
mutual_info_score(df_full_train.role, df_full_train.rarity)

0.08565684995849585

In [178]:
mutual_info_score(df_full_train.weapon, df_full_train.rarity)

0.05177512507839105

In [180]:
mutual_info_score(df_full_train.birthplace, df_full_train.rarity)

0.21564332806403358

In [181]:
mutual_info_score(df_full_train.character, df_full_train.rarity)

0.6730116670092569

In [198]:
# stiill hp is far more influencial to rarity

#now tryin to wrap it up in one function

In [185]:
def mutual_info_rarity_score(series):
    return mutual_info_score(series, df_full_train.rarity)

In [215]:
mi = df_full_train[categorical].apply(mutual_info_rarity_score)
mi = mi.drop(['character', 'rarity'])
mi.sort_values(ascending=False) #this will apply on each column

affiliation    0.235131
birthplace     0.215643
attribute      0.147478
role           0.085657
weapon         0.051775
dtype: float64

In [216]:
# thats how categorical important to predict rarity

# next we gonna talk about numerical

# Feature Importance: Correlation

### notes for ML Zoomcamp 3.7 Youtube