In [1]:
pip install pdfplumber PyPDF2 pandas

Requirement already satisfied: pdfplumber in /home/codespace/.python/current/lib/python3.12/site-packages (0.11.10)
Requirement already satisfied: PyPDF2 in /home/codespace/.python/current/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: pandas in /home/codespace/.python/current/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: pdfminer.six==20260107 in /home/codespace/.python/current/lib/python3.12/site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pdfplumber) (5.13.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.5)
Requirement already satisfied: cryptography>=36.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pdfplumber
from PyPDF2 import PdfReader
import pandas as pd

In [3]:
pdf_path = "Lampiran_Data_Bencana_2024.pdf"

In [4]:
reader = PdfReader(pdf_path)

all_text = []

for page_number, page in enumerate(reader.pages, start=1):
    text = page.extract_text()
    all_text.append({
        "page": page_number,
        "text": text
    })

text_df = pd.DataFrame(all_text)
text_df.head()

   page                                               text
0     1  LAMPIRANLAMPIRAN\nDATA BENCANADATA BENCANAINDO...
1     2  Tabel L1. Kejadian Bencana di Indonesia Tahun ...
2     3  Tabel L2. Kejadian Bencana di Indonesia Tahun ...
3     4  Tabel L3. Kejadian Bencana Indonesia Tahun 202...
4     5  Tabel L3. Kejadian Bencana Indonesia Tahun 202...

In [5]:
print(text_df.loc[0, "text"][:1500])

LAMPIRANLAMPIRAN
DATA BENCANADATA BENCANAINDONESIA 2024INDONESIA 2024
Data Bencana Indonesia 2024
109

In [6]:
all_tables = []

with pdfplumber.open(pdf_path) as pdf:
    for page_number, page in enumerate (pdf.pages, start=1):
        tables = page.extract_tables()

        for table_index, table in enumerate(tables, start=1):
            if table and len(table) > 0: 
                df = pd.DataFrame(table) #gapake header kalo iya pake (table[1:], columns=table[0])
                df["page"] = page_number
                df["table_number"] = table_index
                all_tables.append(df)

In [7]:
if all_tables:
    tables_df = pd.concat(all_tables, ignore_index=True)
else:
    tables_df = pd.DataFrame()

tables_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,page,table_number,12,13,14
0,Jenis Bencana,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN
1,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi &\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,2,1,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,2,1,NaN,NaN,NaN
3,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),2,1,NaN,NaN,NaN

In [8]:
tables_df.columns = [str(col).strip() for col in tables_df.columns]
tables_df = tables_df.dropna(how="all")
tables_df = tables_df.reset_index(drop=True)

tables_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,page,table_number,12,13,14
0,Jenis Bencana,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN
1,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi &\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,2,1,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,2,1,NaN,NaN,NaN
3,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),2,1,NaN,NaN,NaN

In [9]:
page_content = []

with pdfplumber.open(pdf_path) as pdf:
    for page_number, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()
        tables = page.extract_tables()

        page_content.append({
            "page": page_number,
            "text_preview": text[:500] if text else None,
            "num_tables_found": len(tables)
        })

page_summary_df = pd.DataFrame(page_content)
page_summary_df

    page                                       text_preview  num_tables_found
0      1  LLAAMM PPII RRAANN\nDDAATTAA BBEENNCCAANNAA\nI...                 0
1      2  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 2
2      3  Tabel L2. Kejadian Bencana di Indonesia Tahun ...                 1
3      4  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
4      5  Tabel L3. Kejadian Bencana Indonesia Tahun 202...                 1
5      6  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
6      7  Tabel L3. Kejadian Bencana Indonesia Tahun 202...                 1
7      8  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
8      9  Tabel L3. Kejadian Bencana Indonesia Tahun 202...                 1
9     10  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
10    11  Tabel L3. Kejadian Bencana Indonesia Tahun 202...                 1
11    12  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
12    13  Tabel L3. Kejadian Bencana Indonesia Tahun 202...                 1
13    14  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
14    15  Tabel L3. Kejadian Bencana Indonesia Tahun 202...                 1
15    16  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
16    17  Tabel L5. Kejadian Bencana Banjir Tahun 2024 B...                 1
17    18  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
18    19  Tabel L5. Kejadian Bencana Banjir Tahun 2024 B...                 1
19    20  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
20    21  Tabel L5. Kejadian Bencana Banjir Tahun 2024 B...                 1
21    22  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
22    23  Tabel L5. Kejadian Bencana Banjir Tahun 2024 B...                 1
23    24  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
24    25  Tabel L5. Kejadian Bencana Banjir Tahun 2024 B...                 1
25    26  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
26    27  Tabel L5. Kejadian Bencana Banjir Tahun 2024 B...                 1
27    28  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
28    29  Tabel L7. Kejadian Bencana Cuaca Ekstrem Tahun...                 1
29    30  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
30    31  Tabel L7. Kejadian Bencana Cuaca Ekstrem Tahun...                 1
31    32  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
32    33  Tabel L7. Kejadian Bencana Cuaca Ekstrem Tahun...                 1
33    34  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
34    35  Tabel L7. Kejadian Bencana Cuaca Ekstrem Tahun...                 1
35    36  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
36    37  Tabel L9. Kejadian Bencana Tanah Longsor Tahun...                 1
37    38  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
38    39  Tabel L9. Kejadian Bencana Tanah Longsor Tahun...                 1
39    40  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
40    41  Gambar 16.2 Beberapa petugas\nsedang memasang ...                 0
41    42  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 2
42    43  Tabel L11. Kejadian Bencana Gempa Bumi Tahun 2...                 1
43    44  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 2
44    45  Tabel L13. Kejadian Bencana Kekeringan Tahun 2...                 1
45    46  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
46    47  Gambar 16.3 Seorang nenek\nsedang menyirami ta...                 0
47    48  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
48    49  Tabel L15. Kejadian Bencana Kebakaran Hutan da...                 1
49    50  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
50    51  Tabel L15. Kejadian Bencana Kebakaran Hutan da...                 1
51    52  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
52    53  Tabel L15. Kejadian Bencana Kebakaran Hutan da...                 1
53    54  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 1
54    55  Tabel L17. Kejadian Bencana Gelombang Pasang d...                 1
55    56  LAMPIRAN DATA BENCANA INDONESIA TAHUN 2024\nTa...                 2

In [10]:
text_df.to_csv("extracted_pdf2024_text.csv", index=False)
tables_df.to_csv("extracted_tables2024_df.csv", index=False)
page_summary_df.to_csv("extracted_page_summary2024.csv", index=False)

In [11]:
for i, df in enumerate(all_tables, start=1):
    print(f"\n--- Table {i} ---")
    display(df.head())

--- Table 1 ---

,0,1,2,3,4,5,6,7,8,9,10,11,page,table_number
0,Jenis Bencana,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,2,1
1,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi &\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,2,1
2,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,2,1
3,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,2,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),2,1

--- Table 2 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,2,2
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,2,2
2,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,2,2
3,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,2,2
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),2,2

--- Table 3 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,3,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,3,1
2,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,3,1
3,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,3,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),3,1

--- Table 4 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,4,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,4,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,4,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,4,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),4,1

--- Table 5 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,5,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,5,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,5,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,5,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),5,1

--- Table 6 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,6,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,6,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,6,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,6,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),6,1

--- Table 7 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,7,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,7,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,7,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,7,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),7,1

--- Table 8 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,8,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,8,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,8,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,8,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),8,1

--- Table 9 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,9,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,9,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,9,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,9,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),9,1

--- Table 10 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,10,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,10,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,10,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,10,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),10,1

--- Table 11 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,11,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,11,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,11,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,11,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),11,1

--- Table 12 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,12,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,12,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,12,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,12,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),12,1

--- Table 13 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,13,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,13,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,13,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,13,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),13,1

--- Table 14 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,14,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,14,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,14,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,14,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),14,1

--- Table 15 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,15,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka-\nLuka,Mengungsi\n&\nTerdampak,Rumah,NaN,NaN,NaN,Fasillitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,15,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rusak\nBerat,Rusak\nSedang,Rusak\nRingan,Terendam,NaN,NaN,NaN,15,1
3,NaN,NaN,NaN,NaN,NaN,Jiwa,NaN,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,15,1
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),15,1

--- Table 16 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,16,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,16,1
2,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,16,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),16,1
4,11,ACEH,47,3,-,230.712,49,16,41,29.834,1,-,-,16,1

--- Table 17 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,17,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,17,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,17,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),17,1
4,11,ACEH,1101,ACEH SELATAN,5,-,-,25.292,-,-,-,4.339,-,-,-,17,1

--- Table 18 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,18,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,18,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,18,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),18,1
4,,,1225,NIAS BARAT,2,-,,8.545,-,-,-,2.107,-,-,-,18,1

--- Table 19 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,19,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,19,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,19,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),19,1
4,,,1408,SIAK,1,-,-,692,-,-,-,173,-,-,-,19,1

--- Table 20 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,20,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,20,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,20,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),20,1
4,,,1771,KOTA BENGKULU,3,-,-,2.419,-,-,-,466,-,-,-,20,1

--- Table 21 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,21,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,21,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,21,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),21,1
4,,,3210,MAJALENGKA,1,-,-,7.141,-,-,-,2.131,-,-,-,21,1

--- Table 22 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,22,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,22,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,22,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),22,1
4,,,3327,PEMALANG,1,-,-,11.985,-,-,-,1.272,-,-,-,22,1

--- Table 23 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,23,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,23,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,23,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),23,1
4,36,BANTEN,3601,PANDEGLANG,9,1,-,62.939,8,-,22,5.253,-,-,-,23,1

--- Table 24 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,24,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,24,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,24,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),24,1
4,,,6106,KAPUAS HULU,2,-,-,80.714,2,-,-,15.145,-,-,-,24,1

--- Table 25 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,25,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,25,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,25,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),25,1
4,,,6472,KOTA SAMARINDA,7,1,-,2.887,-,-,-,633,-,-,-,25,1

--- Table 26 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,26,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,26,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,26,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),26,1
4,,,7309,MAROS,1,-,-,193.102,-,-,-,,-,-,-,26,1

--- Table 27 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,27,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,27,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,27,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),27,1
4,,,8106,SERAM BAGIAN\nBARAT,5,-,-,3.880,-,-,-,747,-,-,-,27,1

--- Table 28 ---

,0,1,2,3,4,5,6,7,8,9,10,11,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,28,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,28,1
2,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,28,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),28,1
4,11,ACEH,14,2,1,777,44,38,130,2,-,-,28,1

--- Table 29 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,29,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,29,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,29,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),29,1
4,11,ACEH,1102,ACEH TENGGARA,1,-,-,41,4,4,5,-,-,-,29,1

--- Table 30 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,30,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,30,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,30,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),30,1
4,14,RIAU,1401,KAMPAR,2,-,-,518,6,4,50,2,3,-,30,1

--- Table 31 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,31,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,31,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,31,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),31,1
4,32,JAWA BARAT,3201,BOGOR,83,2,13,7.259,122,446,1.211,2,2,-,31,1

--- Table 32 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,32,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,32,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,32,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),32,1
4,,,3319,KUDUS,1,-,-,50,-,-,10,-,-,-,32,1

--- Table 33 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,33,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,33,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,33,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),33,1
4,,,3523,TUBAN,2,-,-,110,-,3,30,-,-,-,33,1

--- Table 34 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,34,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,34,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,34,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),34,1
4,,,5309,NGADA,1,-,-,105,6,20,-,-,-,1,34,1

--- Table 35 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten /\nKota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,35,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,35,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,35,1
3,,,,,,,,,,,,,,,35,1
4,(1),(2),(3)\n7324,(4)\nLUWU TIMUR,(5)\n2,(6)\n-,(7)\n-,(8)\n309,(9)\n39,(10)\n8,(11)\n16,(12)\n-,(13)\n-,(14)\n-,35,1

--- Table 36 ---

,0,1,2,3,4,5,6,7,8,9,10,11,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,36,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,36,1
2,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,36,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),36,1
4,11,ACEH,2,4,1,95,12,10,3,-,-,-,36,1

--- Table 37 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama\nKabupaten/Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,37,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,37,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,37,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),37,1
4,11,ACEH,1104,ACEH TENGAH,1,4,-,66,9,10,-,-,-,-,37,1

--- Table 38 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama\nKabupaten/Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,38,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,38,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,38,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),38,1
4,,,3210,MAJALENGKA,1,1,-,10,-,-,-,-,-,-,38,1

--- Table 39 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama\nKabupaten/Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,39,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,39,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,39,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),39,1
4,,,3579,KOTA BATU,1,-,-,50,-,-,-,-,-,-,39,1

--- Table 40 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama\nKabupaten/Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,40,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,40,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,40,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),40,1
4,75,GORONTALO,7501,GORONTALO,1,1,-,-,-,-,-,-,-,-,40,1

--- Table 41 ---

,0,1,2,3,4,5,6,7,8,9,10,11,page,table_number
0,Kode Wilayah\nProvinsi,Nama Provinsi,Jumlah Kejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,42,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,42,1
2,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,42,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),42,1
4,17,BENGKULU,1,-,-,575,8,19,88,-,3,-,42,1

--- Table 42 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,42,2
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,42,2
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,42,2
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),42,2
4,17,BENGKULU,1701,BENGKULU\nSELATAN,1,-,-,575,8,19,88,-,3,-,42,2

--- Table 43 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,43,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,43,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,43,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),43,1
4,,,3273,KOTA BANDUNG,1,-,-,-,-,-,-,-,-,-,43,1

--- Table 44 ---

,0,1,2,3,page,table_number
0,Kode Wilayah,Nama Provinsi,Jumlah Kejadian,Korban,44,1
1,NaN,NaN,NaN,Mengungsi &\nTerdampak,44,1
2,(1),(2),(3),(4),44,1
3,11,ACEH,1,19407,44,1
4,12,SUMATERA UTARA,2,2455,44,1

--- Table 45 ---

,0,1,2,3,4,5,page,table_number
0,Kode Wilayah\nProvinsi,Nama Provinsi,Kode Wilayah Kabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah Kejadian,Korban,44,2
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,44,2
2,(1),(2),(3),(4),(5),(6),44,2
3,11,ACEH,1106,ACEH BESAR,1,19.407,44,2
4,12,SUMATERA UTARA,1278,KOTA\nGUNUNGSITOLI,2,2.455,44,2

--- Table 46 ---

,0,1,2,3,4,5,page,table_number
0,Kode Wilayah\nProvinsi,Nama Provinsi,Kode Wilayah Kabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah Kejadian,Korban,45,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,45,1
2,(1),(2),(3),(4),(5),(6),45,1
3,,,3216,BEKASI,2,48.591,45,1
4,,,3217,BANDUNG BARAT,1,1.605,45,1

--- Table 47 ---

,0,1,2,3,4,5,page,table_number
0,Kode Wilayah\nProvinsi,Nama Provinsi,Kode Wilayah Kabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah Kejadian,Korban,46,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,46,1
2,(1),(2),(3),(4),(5),(6),46,1
3,,,5206,BIMA,1,23.716,46,1
4,,,5207,SUMBAWA BARAT,1,17.098,46,1

--- Table 48 ---

,0,1,2,3,4,page,table_number
0,Kode Wilayah,Nama Provinsi,Jumlah Kejadian,Korban,Lahan Terbakar (Ha),48,1
1,NaN,NaN,NaN,Mengungsi &\nTerdampak a,NaN,48,1
2,(1),(2),(3),(4),(5),48,1
3,11,ACEH,35,0,"221,795",48,1
4,12,SUMATERA UTARA,170,4,"1371,18",48,1

--- Table 49 ---

,0,1,2,3,4,5,6,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,Jumlah Kejadian,49,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,NaN,49,1
2,(1),(2),(3),(4),(5),(6),(7),49,1
3,11,ACEH,1101,ACEH SELATAN,4,-,"31,7",49,1
4,,,1102,ACEH TENGGARA,3,-,14,49,1

--- Table 50 ---

,0,1,2,3,4,5,6,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,Jumlah Kejadian,50,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,NaN,50,1
2,(1),(2),(3),(4),(5),(6),(7),50,1
3,,,1404,INDRAGIRI HILIR,1,-,"200,8",50,1
4,,,1405,PELALAWAN,1,-,"107,73",50,1

--- Table 51 ---

,0,1,2,3,4,5,6,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,Jumlah Kejadian,51,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,NaN,51,1
2,(1),(2),(3),(4),(5),(6),(7),51,1
3,,,2104,LINGGA,2,-,2,51,1
4,,,2105,KEPULAUAN\nANAMBAS,2,-,"2,5",51,1

--- Table 52 ---

,0,1,2,3,4,5,6,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,Jumlah Kejadian,52,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,NaN,52,1
2,(1),(2),(3),(4),(5),(6),(7),52,1
3,,,3510,BANYUWANGI,9,-,10,52,1
4,,,3511,BONDOWOSO,15,-,2,52,1

--- Table 53 ---

,0,1,2,3,4,5,6,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama Kabupaten\n/ Kota,Jumlah\nKejadian,Korban,Jumlah Kejadian,53,1
1,NaN,NaN,NaN,NaN,NaN,Mengungsi &\nTerdampak,NaN,53,1
2,(1),(2),(3),(4),(5),(6),(7),53,1
3,62,KALIMANTAN\nTENGAH,6201,KOTAWARINGIN\nBARAT,1,-,"14,58",53,1
4,,,6202,KOTAWARINGIN\nTIMUR,1,-,"20,29",53,1

--- Table 54 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,page,table_number
0,Kode\nWilayah\nProvinsi,Nama Provinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,54,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi &\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,54,1
2,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,54,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),54,1
4,13,SUMATERA BARAT,3,-,-,571,3,3,17,59,-,-,-,54,1

--- Table 55 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama\nKabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,55,1
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n&\nTerdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,55,1
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,55,1
3,(1),(2),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),55,1
4,13,SUMATERA\nBARAT,1305,PADANG\nPARIAMAN,1,-,-,565,-,-,1,59,-,-,-,55,1

--- Table 56 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,56,1
1,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,56,1
2,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,56,1
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),56,1
4,13,SUMATERA\nBARAT,3,42,2,6.406,176,12,48,235,-,1,-,56,1

--- Table 57 ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,page,table_number
0,Kode\nWilayah\nProvinsi,Nama\nProvinsi,Kode\nWilayah\nKabupaten\n/ Kota,Nama\nKabupaten/\nKota,Jumlah\nKejadian,Korban,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,56,2
1,NaN,NaN,NaN,NaN,NaN,Meninggal\n& Hilang,Luka /\nSakit,Mengungsi\n& Terdampak,Rumah\nRusak\nBerat,Rumah\nRusak\nSedang,Rumah\nRusak\nRingan,Rumah\nTerendam,Fasilitas\nPendidikan,Fasilitas\nPeribadatan,Fasilitas\nKesehatan,56,2
2,NaN,NaN,NaN,NaN,NaN,(jiwa),NaN,NaN,(unit),NaN,NaN,NaN,NaN,NaN,NaN,56,2
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),,(12),(13),(14),56,2
4,13,SUMATERA\nBARAT,1304,TANAH DATAR,2,42,2,6.114,173,12,3,166,-,1,-,56,2